In [1]:
import numpy as np

In [16]:
a = np.array([1, 2, 3, 4, 5],dtype=np.int32) #int type np array
b = np.array(['a', 'b', 'c', 'd', 'e'],dtype='str') #str type np array
c = np.array([1.1, 2.2, 3.3, 4.4, 5.5],dtype=np.float32) #float type np array

array([1, 2, 3, 4, 5])

In [7]:
# shapes of arrays
print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(5,)
(5,)


In [39]:
# zero array
print('Zeros \n',np.zeros((2,2)))
# empty array
print('Empty \n',np.empty((2,2)))
# eye array
print('Eye \n',np.eye(2))
print('Eye \n',(np.eye(2 , k=1)))

Zeros 
 [[0. 0.]
 [0. 0.]]
Empty 
 [[0. 0.]
 [0. 0.]]
Eye 
 [[1. 0.]
 [0. 1.]]
Eye 
 [[0. 1.]
 [0. 0.]]


In [14]:
# object array 
print('Object \n',np.array([1,2,3,4,5],dtype=object)) #it is possible

Object 
 [1 2 3 4 5]


In [15]:
print('Linspace \n',np.linspace(5,15,5)) #5 equally spaced numbers ranging from 5 to 15

Linspace 
 [ 5.   7.5 10.  12.5 15. ]


In [23]:
# ranging from 1 to 100
a= np.arange(1,101)
print('Range \n',a) 


Range 
 [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [24]:
# Reshape the above array into (100,15)
a = a.reshape(100,15)
print('Reshape \n',a) #not possible because 100*15 = 1500 and 1 to 100 has only 99 elements

ValueError: cannot reshape array of size 100 into shape (100,15)

In [25]:
# Reshape the array into (100,10)
a = a.reshape(100,10) #not possible because 100*10 = 1000 and 1 to 100 has only 99 elements
a

ValueError: cannot reshape array of size 100 into shape (100,10)

In [28]:
# possible reshape
a = a.reshape(10,10)
print('Reshaped\n',a)
# flatten
print('Flatten \n',a.flatten())
# ravel
print('Ravel \n',a.ravel())
# Ravel is faster than flatten() as it does not occupy any memory. Flatten() is comparatively slower than ravel() as it occupies memory


Reshaped
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
Flatten 
 [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
Ravel 
 [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33 

In [34]:
# Take an array [[1 2 3] [4 5 6] [ 7 8 9]]. Sum it along 0 and 1 axis
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Sum along 0 axis \n',a.sum(axis=0))
print('Sum along 1 axis \n',a.sum(axis=1))

Sum along 0 axis 
 [12 15 18]
Sum along 1 axis 
 [ 6 15 24]


In [32]:
# number of bytes used by array
print('Number of bytes used by array \n',a.nbytes)

Number of bytes used by array 
 36


In [35]:
#maximum and minimum values in a 1D array.
a = np.array([1,2,3,4,5,6,7,8,9])
print('Maximum value in array \n',a.max())
print('Minimum value in array \n',a.min())

Maximum value in array 
 9
Minimum value in array 
 1


In [43]:
# maximum and minimum values in 2D array
a = np.arange(10).reshape(2,5)
print('Maximum value in array \n',a.max())
print('Minimum value in array \n',a.min())


Maximum value in array 
 9
Minimum value in array 
 0


In [45]:
# sort 
np.sort(a)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [51]:
# Is * and mul the same as dot product for numpy arrays and matrices?
a = np.array([[0,2],[3,4]])
b = np.array([[5,6],[7,8]])
print('Dot product \n',np.dot(a,b))
print('Mul \n',np.multiply(a,b))
# difference between dot and mul is that dot is matrix multiplication and mul is element wise multiplication

Dot product 
 [[14 16]
 [43 50]]
Mul 
 [[ 0 12]
 [21 32]]


In [52]:
# square root and norm of an array
print('Square root \n',np.sqrt(a))
print('Norm \n',np.linalg.norm(a)) 

Square root 
 [[0.         1.41421356]
 [1.73205081 2.        ]]
Norm 
 5.385164807134504


In [53]:
# std, non-zero, zero values and mean of an array
print('Standard deviation \n',np.std(a))
print('Non zero values \n',np.count_nonzero(a))
print('Zero values \n',np.count_nonzero(a==0))
print('Mean \n',np.mean(a))

Standard deviation 
 1.479019945774904
Non zero values 
 3
Zero values 
 1
Mean 
 2.25


In [56]:
# Convert some angles to radians 
a = np.array([0,30,45,60,90])
print('Radians \n',np.radians(a))
print('Angles \n',np.degrees(np.radians(a)))



Radians 
 [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Degrees 
 [ 0. 30. 45. 60. 90.]


In [57]:
# Save and load some of your arrays
np.save('a',a)
np.load('a.npy')


array([ 0, 30, 45, 60, 90])